record:
  log_dir: '/log/videos'
  log_name: '/test.mp4' #depreciated
  log_name_obs: '/crop.mp4' #depreciated
simulation:
  horizon: 180 #s
  dt: 0.01
  policy_dt: 0.1
  pad_l: 5
  entropy_decay: 1
  epsilon: 0.1
environment:
  height: 10
  width: 20
  resolution: 0.05
  scale_factor: 3
  distance_data: '/assets/distance_data.npy'
  filename: '/assets/map.png'
  urdf: '/assets/map.urdf'
  target_urdf: '/assets/target.urdf'
robot:
  urdf: '/assets/robot.urdf'
  width: 0.5 #x
  depth: 0.5 #y
  height: 0.5 #z
  max_linear_accel: 0.1
  max_linear_vel: 0.2
  max_angular_accel: 0.1
  max_angular_vel: 0.2
lidar:
  density: 0.1 #percentage of max scans to use
  range: 10 #meters
  target_threshold: 3 #meters
  FOV: 360 #degrees
  threads: 0 #-1 is single threaded, 0 is 'all', n is exactly n threads'
rewards:
  detection: 1000
  collision: -1000
  vel_coef: 0.1
  avel_coef: 10
  astar_coef: 1
