record:
  record: False
  log_dir: '/log/videos'
  log_name: '/test.mp4'
  log_name_obs: '/crop.mp4'
simulation:
  horizon: 100 #s
  dt: 0.01
  policy_dt: 0.1
  pad_l: 5
  entropy_decay: 0.997
environment:
  height: 10
  width: 20
  resolution: 0.05
  filename: '/assets/map.png'
  urdf: '/assets/map.urdf'
  target_urdf: '/assets/target.urdf'
robot:
  urdf: '/assets/robot.urdf'
  width: 0.4 #x
  depth: 0.4 #y
  height: 0.4 #z
  max_linear_accel: 0.1
  max_linear_vel: 0.2
  max_angular_accel: 0.1
  max_angular_vel: 0.2
lidar:
  density: 0.2
  range: 10 #meters
  FOV: 120 #degrees
  threads: 0 #-1 is single threaded, 0 is 'all', n is exactly n threads'
rewards:
  detection: 100
